// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuihBLKSyOLsoXzPk1Bp7IwPUoSt2g2Qg',
    appId: '1:402313975964:web:8bcefe4e97e562d75bb559',
    messagingSenderId: '402313975964',
    projectId: 'life-of-flowers',
    authDomain: 'life-of-flowers.firebaseapp.com',
    storageBucket: 'life-of-flowers.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHItHnN8kLWuoO9RbsFJt8kCNla76Dkjg',
    appId: '1:402313975964:android:55435cc43ff69b4f5bb559',
    messagingSenderId: '402313975964',
    projectId: 'life-of-flowers',
    storageBucket: 'life-of-flowers.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkM_AN66YywbPSXBH0U2WZSRcJfxyvfu0',
    appId: '1:402313975964:ios:0549847d7964fb3c5bb559',
    messagingSenderId: '402313975964',
    projectId: 'life-of-flowers',
    storageBucket: 'life-of-flowers.appspot.com',
    iosClientId: '402313975964-bdc56lb9ptbpdg9kp1rf0m51b06d2ss4.apps.googleusercontent.com',
    iosBundleId: 'za.co.wethinkcode.widgetsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkM_AN66YywbPSXBH0U2WZSRcJfxyvfu0',
    appId: '1:402313975964:ios:0549847d7964fb3c5bb559',
    messagingSenderId: '402313975964',
    projectId: 'life-of-flowers',
    storageBucket: 'life-of-flowers.appspot.com',
    iosClientId: '402313975964-bdc56lb9ptbpdg9kp1rf0m51b06d2ss4.apps.googleusercontent.com',
    iosBundleId: 'za.co.wethinkcode.widgetsApp',
  );
}
